### ISSUE TITLE
Incorrect Dependency and Class Not found

### ISSUE THREAD

**Issue by yoga80** [gwenshap/kafka-streams-wordcount#5]
Maven complained about the originally included dependency 

        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams</artifactId>
            <version>0.10.3.0-SNAPSHOT</version>
        </dependency>

I updated to 

        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams</artifactId>
            <version>0.11.0.0</version>
        </dependency>

However running the code throws 

Caused by: java.lang.ClassNotFoundException: org.apache.kafka.streams.processor.TopologyBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

Any idea as to how to resolve?

**Comment by ryangdb** [comment]
I also received a similar same error whilst trying to run this program: 

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/kafka/common/utils/LogContext
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:630)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:610)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:557)
	at WordCountApplication.main(WordCountApplication.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.utils.LogContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 9 more

Did you find a solution?
